### ISSUE TITLE
Traits not working

### ISSUE THREAD

**Issue by SebbyLikesCats** [ZioPao/The-Only-Cure#31] opened 2024-05-03 23:56 UTC
It doesnt show

**Comment by SebbyLikesCats** [comment] 2024-05-03 23:57
It still shows the arm

**Comment by ZioPao** [comment] 2024-05-03 23:59
Hi, I really need more info. Could you add some screenshots of the health panel? Also, are you running some additional mods?

**Comment by SebbyLikesCats** [comment] 2024-05-04 02:09
No Unless clothing mods count I dont have any model changing mods on

**Comment by ZioPao** [comment] 2024-05-04 02:10
> No Unless clothing mods count I dont have any model changing mods on

They do count. Could you add a screenshot to show how it looks? If you don't have any clothes on, does the amputation shows up?

**Comment by SebbyLikesCats** [comment] 2024-05-04 02:11
lemme load up the save

**Comment by SebbyLikesCats** [comment] 2024-05-04 02:21
![Screenshot 2024-05-03 192104](https://github.com/ZioPao/The-Only-Cure/assets/168876558/232a0698-468c-4d0d-979d-07b7351f746e)


> > No Unless clothing mods count I dont have any model changing mods on
> 
> They do count. Could you add a screenshot to show how it looks? If you don't have any clothes on, does the amputation shows up?

**Comment by SebbyLikesCats** [comment] 2024-05-04 02:22
So?
?????????????????????????

**Comment by ZioPao** [comment] 2024-05-04 02:24
Doesn't even look like you've got the mod enabled. A couple of questions:
1) Is this Single player or Multiplayer?
2) Can you provide your modlist? 
3) Which limb did you cut? Did some errors appear when you did?

**Comment by SebbyLikesCats** [comment] 2024-05-04 02:27
> Doesn't even look like you've got the mod enabled. A couple of questions:
> 
> 1. Is this Single player or Multiplayer?
> 2. Can you provide your modlist?
> 3. Which limb did you cut? Did some errors appear when you did?

I got it Enabled and Its Single Player and I clicked the amputee Trait and heres my mod list (itll take awhile)

**Comment by SebbyLikesCats** [comment] 2024-05-04 02:27
Oh and No errors

**Comment by SebbyLikesCats** [comment] 2024-05-04 02:28
> Doesn't even look like you've got the mod enabled. A couple of questions:
> 
> 1. Is this Single player or Multiplayer?
> 2. Can you provide your modlist?
> 3. Which limb did you cut? Did some errors appear when you did?

also Is there any unsupported mods?
other than the orginial

**Comment by SebbyLikesCats** [comment] 2024-05-04 02:28
> > No Unless clothing mods count I dont have any model changing mods on
> 
> They do count. Could you add a screenshot to show how it looks? If you don't have any clothes on, does the amputation shows up?

**Comment by SebbyLikesCats** [comment] 2024-05-04 02:43
![Screenshot 2024-05-03 194218](https://github.com/ZioPao/The-Only-Cure/assets/168876558/5cec1f64-5612-4149-b5ab-b2892eb2ca71)
![Screenshot 2024-05-03 194232](https://github.com/ZioPao/The-Only-Cure/assets/168876558/24026d4f-d9bb-498b-b1cc-55d21399ac7b)
![Screenshot 2024-05-03 194252](https://github.com/ZioPao/The-Only-Cure/assets/168876558/ca72a34e-ab56-45d0-88b2-24235efe1fb4)
![Screenshot 2024-05-03 194324](https://github.com/ZioPao/The-Only-Cure/assets/168876558/12bd016d-2895-4696-beb8-f3d2a754b58c)

**Comment by SebbyLikesCats** [comment] 2024-05-04 02:44
![Uploading Screenshot 2024-05-03 194400.png…]()

**Comment by SebbyLikesCats** [comment] 2024-05-04 04:19
never mind its only a problem with the trait

**Comment by SebbyLikesCats** [comment] 2024-05-04 04:19
not cutting it off manually

**Comment by ZioPao** [comment] 2024-05-04 13:41
Please, write in one single post and not like this, it makes things impossible to keep track of.

So, the problem is related ONLY to the trait, is that correct?

**Comment by Chihuahuaeater** [comment] 2024-05-04 15:03
Yes that is the problem, I've been having the same problem but I didn't report it because I didn't want to make a github account.

**Comment by ZioPao** [comment] 2024-05-04 15:07
> Yes that is the problem, I've been having the same problem but I didn't report it because I didn't want to make a github account. Whenever I start with the trait I still have both of my arms.

A fix is coming shortly, sorry for the bug.

**Comment by Chihuahuaeater** [comment] 2024-05-04 15:28
If you could let me know when its fixed that would be cool. Just wanna compliment your mod too its pretty awesome dude. Its quite unique hope you keep updating it and maybe add something like prosthetic tiers but thats up to you keep it up.

**Comment by ZioPao** [comment] 2024-05-04 16:03
> If you could let me know when its fixed that would be cool. Just wanna compliment your mod too its pretty awesome dude. Its quite unique hope you keep updating it and maybe add something like prosthetic tiers but thats up to you keep it up.

Thank you for the compliment, I really appreciate it :) 
The fix has been uploaded on the workshop, I will wait for some reports and then close the issue.

**Comment by Chihuahuaeater** [comment] 2024-05-04 17:13
Update up and its good I don't see anything thats necessary bad or game breaking but there is an amputee option that doesn't do anything and the other actual amputee traits that do work don't that descriptions I'm guessing youre still working on that. Heres a screenshot I'm running more traits so I think that might be conflicting a little.

![a7kd3FO - Imgur](https://github.com/ZioPao/The-Only-Cure/assets/168919055/95001c72-28e5-488b-8fbf-feb60946e370)

**Comment by ZioPao** [comment] 2024-05-04 17:19
> Update up and its good I don't see anything thats necessary bad or game breaking but there is an amputee option that doesn't do anything and the other actual amputee traits that do work don't that descriptions I'm guessing youre still working on that. Heres a screenshot I'm running more traits so I think that might be conflicting a little.
> 
> ![a7kd3FO - Imgur](https://private-user-images.githubusercontent.com/168919055/327964033-95001c72-28e5-488b-8fbf-feb60946e370.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NDMxNDUsIm5iZiI6MTcxNDg0Mjg0NSwicGF0aCI6Ii8xNjg5MTkwNTUvMzI3OTY0MDMzLTk1MDAxYzcyLTI4ZTUtNDg4Yi04ZmJmLWZlYjYwOTQ2ZTM3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxNzE0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjEyMjdhYTc5NWI3NjRmNjU1MTRmOTRlM2MzYzY0MTU1MDc4NDViMWRmYmUwNmMwOGFiOGIxZmU4OTEyODAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ihbGpLiLvlAhskNxqAa_pN3iIagdg2tOgugC0ALikxU)

That 'amputee' trait comes from More Traits. I checked and it's getting enabled because they're checking for the old MOD ID of The Only Cure (It went from Amputation to TheOnlyCure). 
That's something that should be updated from their side. Unfortunately it's not something I can fix, you should report it to the More Traits dev.

**Closed** 2024-05-04 18:12 UTC
Labels: bug
